### ISSUE TITLE
Use of QScrollBar causes significant CPU spike

### ISSUE THREAD

**Issue by ghost** [copperspice/copperspice#102] opened 2019-05-04 08:44 UTC
Introducing a scrollbar in a dock widget causes significant CPU spike. Here's a sample to demonstrate the issue.

```
#include <QtGui/QApplication>
#include <QtGui/QMainWindow>
#include <QtGui/QDockWidget>
#include <QtGui/QScrollBar>
#include <QtCore/QDebug>
#include <Windows.h>

int APIENTRY WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, PSTR lpCmdLine, INT nCmdShow)
{
  QApplication a(__argc, __argv);
  QMainWindow mw;

  QDockWidget *dockWidget = new QDockWidget();
  mw.addDockWidget(Qt::TopDockWidgetArea, dockWidget);

  QWidget *widget = new QWidget();
  dockWidget->setWidget(widget);

  QScrollBar *scrollbar = new QScrollBar(widget);
  scrollbar->setOrientation(Qt::Horizontal);

  mw.show();
  return a.exec();
}
```

**Comment by janwilmans** [comment] 2019-05-04 08:52
Thanks for reporting this, it will be investigated, however expect a delay
because I'm travelling (cppnow) and we're working on finishing off a
feature branch.

**Comment by agserm** [comment] 2019-05-05 17:07
Thank you for reporting this, This is great timing. The new branch we are working on includes major changes to the GUI library so we will test this right away.

**Comment by de1001** [comment] 2019-05-05 21:10
I have been digging to figure out the root cause of the problem and as it turns out it might not have anything specific to do with ```QScrollBar``` itself. I am able to reproduce the problem with use of ```QLineEdit``` as well.

```
int APIENTRY WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, PSTR lpCmdLine, INT nCmdShow)
{
  QApplication a(__argc, __argv);

  QWidget *widget = new QWidget();
  QLineEdit *lineEdit = new QLineEdit(widget);

  QMainWindow mw;
  mw.setCentralWidget(widget);
  mw.show();

  return a.exec();
}
```

This program consistently consumes 25% of my CPU on my 8 core machine.

@agserm Any chance I can get my hands on a pre-release?

**Comment by agserm** [comment] 2019-05-06 05:01
Thanks for the update, this is great information. We are working as quickly as possible to get the branch into public testing. We still have two build issues which should be resolved in roughly the next two weeks. I will update this issue as soon as possible.

**Comment by agserm** [comment] 2019-05-27 14:20
We are cleaning up the remaining commits and will have something ready for testing in the next day or two.

**Comment by agserm** [comment] 2019-10-26 17:02
Closing this ticket since the resolution has been pushed to master and will be in the next release of CopperSpice.

**Closed by agserm** 2019-10-26 17:02 UTC
