### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by hs-apotell** [copperspice/copperspice#142] opened 2020-04-12 06:35 UTC
I just pulled down master @ 32f8144507834fcea042fe943284c8acfc85e8ee and noticing some severe performance degradation. Unfortunately, my last pull was almost 3 months back so can't really confirm as to what during this period might have introduced the issue.

What I am noticing is that the application takes much longer (10+ seconds) to launch compared to 3+ seconds with previous build. I am also noticing some controls misbehaving like for instance, QLineEdit doesn't reflect typed characters for 5+ seconds.

**Comment by janwilmans** [comment] 2020-04-12 09:54
The 2-3 second startup time is a known issue, but the 10+ seconds I can only explain in debug mode, are you using debug or release configuration?

**Comment by hs-apotell** [comment] 2020-04-12 10:38
The startup time issue is in debug mode. Release does seem relatively better.
QLineEdit issue is reproducible in release mode as well.

**Comment by janwilmans** [comment] 2020-04-12 11:59
Thanks, so as far as I know the startup delay is not a degradation, it was always there. We're working it though because I recognize its real problem and debug configuration is important too

**Comment by bgeller** [comment] 2020-04-12 22:19
Can you let us know what platform, the compiler and version you are building with.  It would be very helpful if you could create a small standalone test case.  As mentioned this is not something we have experienced.  Thanks for you continued testing.

**Comment by hs-apotell** [comment] 2020-04-13 05:12
Platform - Windows 10 Version 1909 Build 18363.720
Compiler - Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64
Change - 32f8144507834fcea042fe943284c8acfc85e8ee

Simple example to reproduce the issue.

`
int main()
{
  QApplication a(__argc, __argv);

  QWidget *widget = new QWidget();
  QLineEdit *lineEdit = new QLineEdit(widget);

  QMainWindow mw;
  mw.setCentralWidget(widget);
  mw.show();

  return a.exec();
}
`

Once the application launches, click on the edit box and immediately start typing. In debug mode, you should notice a huge lag in the characters visually showing up.

P.S. I haven't tried the same in release build just yet.

**Comment by bgeller** [comment] 2020-04-26 04:55
CopperSpice 1.6.3 was released a few days ago.  Please check this out and see if you are still having any slow down issues.  Currently none of our tests were able to reproduce this.

**Comment by jvoosten** [comment] 2020-09-18 16:26
I am using CopperSpcie 1.6.3 for a new project and noticed a long delay time on startup as well (and so did my fellow developers). Using Visual Studio Community 2019 version 16.7.3. The constructor of my MainWindow is called quickly (I see that in the debug output), then it takes anywhere form 5 to 20 seconds before the application window is actually shown.

**Comment by bgeller** [comment] 2020-09-18 17:22
Are you using the pre-built binaries from our download site or did you build from source?  One of the things we are wondering is if you have debug turned on. Is there any way you create a small sample program which simulates this issue?  

We want to reproduce this and see what we can do. 

Barbara

**Comment by jvoosten** [comment] 2020-09-18 20:26
We are using the pre-built binaries from your site; target is 64 bit.  I have created a sample and also narrowed the problem down to addMenu() (see the attached zip) 

[sandbox.zip](https://github.com/copperspice/copperspice/files/5247937/sandbox.zip)

When I comment out line 24-26 the application starts up quickly. With the lines intact there is a 20 second delay which is fairly consistent:

`[     0] Start`
`QWindowsContext::setProcessDpiAwareness(): Dpi = 2`
`[   165] App created`
`[   347] MainWindow created`
`[   348] Before MainWindow::show`
`[ 22235] After MainWindow::show`

This is with the Debug build. However, a Release build does start quickly:

`[   872] After MainWindow::show`

I also noticed that when I start the Debug version from inside Visual Studio, there is a gradual increase in memory during those 20 seconds.

**Comment by janwilmans** [comment] 2020-09-18 21:59
@jvoosten I can reproduce your issue. Did you also see this before 1.6.3? or was 1.6.3 the first version you tried?

**Comment by jvoosten** [comment] 2020-09-20 16:05
> @jvoosten I can reproduce your issue. Did you also see this before 1.6.3? or was 1.6.3 the first version you tried?

@janwilmans 1.6.3 was the first version I tried. Have not had the time to try other versions.

**Comment by janwilmans** [comment] 2020-10-02 22:44
Update: we're working to fix this issue, it seems to be windows specific, and very prominent in debug configuration, but also (but less severely)  affecting release configurations.

**Comment by janwilmans** [comment] 2020-11-21 12:52
@hs-apotell thanks for reporting! @jvoosten thanks for testing! This was fixed along with the refactored QFontDatabase, so we're closing this issue.

**Closed by janwilmans** 2020-11-21 12:52 UTC
