### ISSUE TITLE
Build fails with Clang on Windows (VS2019)

### ISSUE THREAD

**Issue by TheRealJokerMan** [copperspice/copperspice#139] opened 2020-02-24 13:57 UTC
I'm trying to build head with the [Clang that comes](https://devblogs.microsoft.com/cppblog/clang-llvm-support-in-visual-studio/) with VS 2019. This is the output I get:

```
C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\Llvm\bin\clang-cl.exe  /nologo -TP   @src\core\CMakeFiles\CsCore.dir\kernel\qpointer.cpp.obj.rsp /showIncludes /Fosrc\core\CMakeFiles\CsCore.dir\kernel\qpointer.cpp.obj /Fdsrc\core\CMakeFiles\CsCore.dir\ -c ..\..\..\src\core\kernel\qpointer.cpp
  In file included from ..\..\..\src\core\kernel\qpointer.cpp:24:
  In file included from ..\..\..\src\core\kernel\qpointer.h:27:
  In file included from ..\..\..\src\core\tools\qsharedpointer.h:24:
  In file included from ..\..\..\src\core\global\qnamespace.h:28:
  In file included from ..\..\..\src\core\kernel\csobject_macro.h:27:
  In file included from include\QtCore\cs_signal.h:33:
  In file included from include\QtCore\cs_slot.h:29:
C:\Users\jamie.kenyon\Downloads\copperspice-master\out\build\x64-Debug\include\QtCore\rcu_guarded.hpp(141,7): error : no matching constructor for initialization of 'libguarded::rcu_list<CsSignal::SignalBase::ConnectStruct, std::mutex, std::allocator<CsSignal::SignalBase::ConnectStruct> >'
      : m_obj(std::forward<Us>(data)...)
        ^     ~~~~~~~~~~~~~~~~~~~~~~
  C:\Users\jamie.kenyon\Downloads\copperspice-master\out\build\x64-Debug\include\QtCore\cs_signal.h(82,22): note: in instantiation of function template specialization 'libguarded::rcu_guarded<libguarded::rcu_list<CsSignal::SignalBase::ConnectStruct, std::mutex, std::allocator<CsSignal::SignalBase::ConnectStruct> > >::rcu_guarded<libguarded::rcu_guarded<libguarded::rcu_list<CsSignal::SignalBase::ConnectStruct, std::mutex, std::allocator<CsSignal::SignalBase::ConnectStruct> > > &>' requested here
  class LIB_SIG_EXPORT SignalBase
                       ^
  C:\Users\jamie.kenyon\Downloads\copperspice-master\out\build\x64-Debug\include\QtCore\rcu_list.hpp(74,14): note: candidate constructor not viable: no known conversion from 'libguarded::rcu_guarded<libguarded::rcu_list<CsSignal::SignalBase::ConnectStruct, std::mutex, std::allocator<CsSignal::SignalBase::ConnectStruct> > >' to 'const std::allocator<CsSignal::SignalBase::ConnectStruct>' for 1st argument
      explicit rcu_list(const Alloc &alloc);
               ^
  C:\Users\jamie.kenyon\Downloads\copperspice-master\out\build\x64-Debug\include\QtCore\rcu_list.hpp(76,5): note: candidate constructor not viable: no known conversion from 'libguarded::rcu_guarded<libguarded::rcu_list<CsSignal::SignalBase::ConnectStruct, std::mutex, std::allocator<CsSignal::SignalBase::ConnectStruct> > >' to 'const libguarded::rcu_list<CsSignal::SignalBase::ConnectStruct, std::mutex, std::allocator<CsSignal::SignalBase::ConnectStruct> >' for 1st argument
      rcu_list(const rcu_list &) = delete;
      ^
  C:\Users\jamie.kenyon\Downloads\copperspice-master\out\build\x64-Debug\include\QtCore\rcu_list.hpp(77,5): note: candidate constructor not viable: no known conversion from 'libguarded::rcu_guarded<libguarded::rcu_list<CsSignal::SignalBase::ConnectStruct, std::mutex, std::allocator<CsSignal::SignalBase::ConnectStruct> > >' to 'libguarded::rcu_list<CsSignal::SignalBase::ConnectStruct, std::mutex, std::allocator<CsSignal::SignalBase::ConnectStruct> >' for 1st argument
      rcu_list(rcu_list &&)      = delete;
      ^
  C:\Users\jamie.kenyon\Downloads\copperspice-master\out\build\x64-Debug\include\QtCore\rcu_list.hpp(73,5): note: candidate constructor not viable: requires 0 arguments, but 1 was provided
      rcu_list();
      ^
  1 error generated.
```

NB: I had to reorder CMakeLists.txt, L71 first, like this:

```
if(MSVC)
   enable_language(ASM_MASM)
   set(target "MSVC")

elseif(CMAKE_CXX_COMPILER_ID MATCHES "(GNU|Clang|AppleClang)")
   execute_process(
      COMMAND ${CMAKE_CXX_COMPILER} -dumpmachine
      OUTPUT_VARIABLE DUMPMACHINE_OUTPUT
      RESULT_VARIABLE DUMPMACHINE_EXITCODE
      OUTPUT_STRIP_TRAILING_WHITESPACE
   )
```

**Comment by janwilmans** [comment] 2020-02-25 20:11
Thank for reporting, I will take a look at this.

**Comment by agserm** [comment] 2020-03-02 02:50
We went ahead and merged the CMakeLists change in aca928f. Can you confirm whether this resolves the problem or if the error log you provided is what resulted after the CMakeLists file was updated?

**Comment by TheRealJokerMan** [comment] 2020-03-02 07:54
Thanks for the CMakeLists.txt change @agserm. Unfortunately, it doesn't resolve the build issue. I've attached all of the output for you.
 
[build_output.log](https://github.com/copperspice/copperspice/files/4274085/build_output.log)

**Comment by TheRealJokerMan** [comment] 2020-03-04 17:03
I don't know if this helps at all, but I've attached the [CMakeSettings.json](https://github.com/copperspice/copperspice/files/4288595/CMakeSettings.json.txt) I'm using to build copperspice.

I'm just putting this in the root of the checkout.

**Comment by janwilmans** [comment] 2020-03-04 20:43
@TheRealJokerMan can you show us the output of the cmake 'generate' step? 
Also, did you use any tools to install libraries/dependencies?

**Comment by TheRealJokerMan** [comment] 2020-03-04 22:42
Sure thing @janwilmans, I've attached it for you.

[CMakeOutput.txt](https://github.com/copperspice/copperspice/files/4289991/CMakeOutput.txt)

I haven't gotten round to dealing with the dependencies yet I'm afraid. I'm just download copperspice from GitHub, putting the CMakeSettings.json in the root and then opening with VS2019.

**Comment by hs-apotell** [comment] 2021-01-13 23:47
Any update on this?

**Comment by bgeller** [comment] 2021-01-16 21:32
We had a CopperSpice team meeting and Jan is back on this.  If there is any more debug information anyone has please let us know.

**Comment by TheRealJokerMan** [comment] 2021-01-16 21:45
I think I've reported all I can. Download via GitHub. Open top-level CMakeLists.txt in VS2019 with clang-cl installed. 

I'll try again and see if there's anything more I can add to this.

**Comment by agserm** [comment] 2021-01-17 01:43
We have done some initial work on this issue, and found out why the copy constructor problem occurs. This appears to happen only on clang-cl and we are testing some solutions. We also found code in other CS libraries where, when compiling with clang-cl we need to find a way to treat it as if we are on MSVC. This is not a trivial change but it is also definitely possible.

This has been put on our roadmap.

**Comment by hs-apotell** [comment] 2021-02-02 11:11
To add some additional information - Ubuntu + Clang builds fail as well.

Build environment - Ubuntu 18 (bionic) + Clang 6.0.0

Most of the errors seem related to recent change to QVariant and private subclassing.

**Comment by janwilmans** [comment] 2021-02-02 12:51
please see https://www.copperspice.com/docs/cs_overview/supported-platforms.html for supported platforms.
gcc 8.4.0 is required on Ubuntu 18.04 (Bionic Beaver).

**Comment by gvanem** [comment] 2021-03-17 10:29
@agserm 

> We also found code in other CS libraries where, when compiling with clang-cl we need to find a way to treat it as if 
> we are on MSVC. 

That would normally be the `-fms-compatibility` option. Even with this, clang-cl fails. It's because of the definition 
of ` LIB_SIG_EXPORT`. And other `x_EXPORT`definitions.  Trying an all-static build of CsCore by patching:
```diff
--- a/core/signal/cs_macro.h 2021-03-12 09:11:27
+++ b/core/signal/cs_macro.h 2021-03-17 11:12:21
@@ -19,7 +19,7 @@
 #ifndef LIB_CS_MACRO_H
 #define LIB_CS_MACRO_H

-#ifdef _WIN32
+#if defined(_WIN32) && !defined(STATIC_LIB_CORE)

 #ifdef BUILDING_LIB_CS_SIGNAL
 # define LIB_SIG_EXPORT     __declspec(dllexport)
```

(same for the other `cs_*.h`). Then `clang-cl` compiles most Core stuff fine.

I also noted that with MSVC-2019, I get tons of `4273` warnings because of the ` LIB_SIG_EXPORT == __declspec(dllexport)`.
That seems to be the cause of `clang-cl` failing and MSVC just give warnings.

It would be nice if all such `dllexport` / `dllimport` stuff could be set in **one** file only. How about `qexport.h`?

**Comment by bgeller** [comment] 2021-03-17 18:30
** Issue One
Please note that on our supported platforms page in the **CS Overview documentation** we do not list clang-cl as a compiler for MSVC.  We do support and test in our CI system using the cl.exe compiler for MSVC. 

As noted earlier in this thread adding support for clang-cl is not just a few simple changes.  There are huge incompatibilities between clang-cl and cl.  This is on our road map and something which will be addressed as more CopperSpice users require this compiler. 

The CS team did review this and it is not just a quick change in the signal macro. There are other low level things to consider. 

** Issue Two
Building CS statically is a completely different issue and not related to clang-cl. Right now CS does not support a statically linked build.  Plugins and RCC ( used to embed resources ) are extremely complicated to build statically. 

If you want to work on a static build we can work with you, however I would suggest using cl as your MSVC compiler. Otherwise you will be battling two issues that will have very different solutions.

We are aware of the massive number of warnings in MSVC and we have worked with them a bit. Keep in mind Microsoft was late to the game with modern C++ support.  The best option may be to turn off warnings for anything in categories like 4250 and 4251.

**Comment by hs-apotell** [comment] 2021-03-17 21:06
> The CS team did review this and it is not just a quick change in the signal macro. There are other low level things to consider.

For clarification, would the Clang support be dependent on
* new Clang release with features required to build CopperSpice, or
* CopperSpice needs to do things differently to make code compatible with Clang i.e. existing version of Clang

Basically, trying to understand whether CopperSpice is using non-standard features unsupported by Clang or Clang is missing features or have deviated from standard raising these issues for CopperSpice. Would a newer Clang release fix any of these issues? Or, is the resolution all on the CopperSpice team?

Regardless, Clang is an important compiler to support. Most of our internal projects have been moving away from cl/gcc and closer to Clang.

**Comment by bgeller** [comment] 2021-03-17 21:36
We have no issues building CS with clang, GCC, or MinGW and our CI uses these compiler for several different operating systems. You can see the exact details of which compiler we built with for each platform.  

https://www.copperspice.com/docs/cs_overview/supported-platforms.html

There are issues on MSVC when using clang-cl since Microsoft does their own thing. They deviated from the standard heavily and now they are sort of stuck in a bad place. This is actually nothing new for MS and compliance has always been an issue on their end.  The CopperSpice libraries ares part of the MS compliance testing which provide feedback for them. 

It was a huge struggle to get CS to build with MSVC and this had nothing to do with our code.  They simply had not implemented enough of the C++ standard and they tend to lag behind other compilers. 

The clang-cl compiler MSVC can use is not simply clang and therefore not a drop in replacement. We strongly believe MS will keep improving clang-cl but it is not there yet. The same holds true for clang on Windows. 

For right now I would strongly suggest using cl with MSVC. If you are not using MSVC then one of our suggested versions of MinGW.  It is much better to use a compiler that is known to work than to jump to something which is not production ready.

**Comment by hs-apotell** [comment] 2021-03-18 02:45
@bgeller Appreciate the detailed information. I wasn't aware of there being a different clang-cl by M$. I assumed it was "the" Clang compiler. I am more interested in the Clang compiler. The last time I tried building it on Ubuntu 18 using Clang I had run into compile issues. I am going to give that a shot once again.

**Comment by agserm** [comment] 2021-03-18 03:04
@hs-apotell, I have a feeling there are lots of developers who do not know these fine details. In fact, clang-cl is a port of clang to the MSVC ABI which is intended to be bug-compatible with cl.exe, which is a bit strange when you think about it.

While our CI only does a GCC build on Ubuntu 18, there are other platforms where we build with various versions of clang. On my dev machine, I routinely test with clang 11. We are adding some newer versions of Fedora to our CI soon and it sounds like we should test clang there as well to make it official. If you run into any issues building with clang on a non-Windows platform please open a separate ticket to track those and we will take a look.

**Comment by bgeller** [comment] 2022-06-08 02:30
Closing since this issue appears to be resolved.  Noting that building with "clang-cl"  is not supported. Building CS with clang is supported and has been tested in our CI on multiple platforms. Please open a new issue if anything here persists.

**Closed by bgeller** 2022-06-08 02:30 UTC
