### ISSUE TITLE
Application extremely slow with setStyleSheet set

### ISSUE THREAD

**Issue by hs-apotell** [copperspice/copperspice#279] opened 2023-07-24 23:49 UTC
I am building a simple application and would like to support dark mode. I used [QDarkStyleSheet](https://github.com/Apotell/QDarkStyleSheet) project to add dark style sheet to my project. The application gets extremely slow to launch. Once launched, however, the performance is not impacted.

I have tried with merely a `QMainWindow` in the application (basically the bare minimum) to eliminate anything that my application might be doing but the issue seems to be withe style sheet parsing logic - it's just extremely slow.

**Comment by bgeller** [comment] 2023-07-25 09:36
Can you look at the style sheet example in our KitchenSink demo to see if it is slow for you.  Another test is to remove various style sheet rules to find out exactly which one(s) are causing your speed issues when loading.

What platform are you building for and which compiler. Also, what CPU do you have and how much memory is installed on the target system.

**Comment by bgeller** [comment] 2023-07-31 04:23
Our initial belief is the speed issues are not really a style sheet problem since the delay is worse with larger files. Most likely this there is an index which should be an iterator.  We have noted this as something to review.

**Comment by ThomasKrenn** [comment] 2023-07-31 19:54
The issue raised by @hs-apotell and the issue discussed here:

[issue 169](https://github.com/copperspice/copperspice/issues/169)

are closely related.

The root cause for both issues is the same.

**Comment by bgeller** [comment] 2023-07-31 20:16
It is possible however there is no way to know they are the same problem until someone digs through the source code. Again, this is most likely an index vs iterator issue. We have seen this kind of issue before.

**Comment by ThomasKrenn** [comment] 2023-07-31 22:30
My comment above is based on a performance analysis (not only digging through the source.)

Why guessing when the issue can be reproduced without great effort? With the help of a decent profiler it's matter of minutes to get to the root of the problem.

Sure, using a character iterator for the CSS parser is a possible workaround. But once the root cause is understood a better solution will solve not only this issue but also several others and improve the performance of copperspice application as a whole.

**Comment by bgeller** [comment] 2023-08-01 03:30
Reproducing something not provide a solution but it does help provide a good test so when a solution is fin. Profilers are intended to locate areas of potential 

To fix the code someone will need to try a few different ideas and find an optimized approach. 

If you believe you have a good idea about how to resolve either of these issues please submit a pull request.

**Comment by bgeller** [comment] 2023-08-01 04:02
Reproducing something is not intended to provide a solution. It is required so you have a good test case.  Profilers are used to help diagnose memory issues and verify how well the code is performing.

To fix the code someone will need to try a few different ideas and then find an optimized approach.

If you believe you have a good idea about how to resolve either of these issues please submit a pull request. Someone on the CS team will review and then test the code. Once it is verified the new code will be merged into the code base. 

It would wonderful to have either one of you work on this code and we look forward to your contributions.

**Comment by agserm** [comment] 2023-09-08 16:49
Your PR has been merged, thank you for your contribution.

**Closed by agserm** 2023-09-08 16:49 UTC
