### ISSUE TITLE
Crashed in Debug for MSVC 2022

### ISSUE THREAD

**Issue by sngy844** [copperspice/copperspice#260] opened 2023-04-20 14:38 UTC
Crashed with error: `D:\a\_work\1\s\src\vctools\crt\github\stl\src\mutex.cpp(163): unlock of unowned mutex`
Steps to reproduce
- Compile app in Debug mode using MSVC 2022
- Link with CopperSpice debug libs and debug runtime dlls. Tried both precompiled dlls and build copperspice myself. Already double checked to link to correct version.

app test code
```c++
#include <QApplication>
#include <Qpushbutton>
#include <Qmainwindow>
#include <QDebug>
int main(int argc, char ** argv){
	QApplication app(argc, argv);
	
	QPushButton button("This is a push button!",nullptr);
	button.show();

	QMainWindow w;
	//w.show();
	QObject::connect(&button, &QPushButton::clicked, &w, [&w](bool b) { qDebug() << "Test"; });

	return app.exec();
}
```

cmake
```
cmake_minimum_required(VERSION 3.16)

project(HelloLunch)
find_package(CopperSpice REQUIRED)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_INCLUDE_DIRECTORIES_BEFORE ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)

add_executable(main main.cpp)
target_link_libraries(main CopperSpice::CsCore  CopperSpice::CsGui)
```

Error when hover the mouse on pushbutton: 
![image](https://user-images.githubusercontent.com/105007980/233400283-f535b74a-7cb9-4a77-82e6-fbe2b29defb0.png)

**Comment by agserm** [comment] 2023-04-20 18:26
This looks like a duplicate of #251, which we have been able to repeat. Thank you for providing additional information, this is in our queue.

**Comment by agserm** [comment] 2023-05-08 03:13
This issue has been resolved in SHA ca5a823.

**Closed by agserm** 2023-05-08 03:13 UTC
Labels: duplicate
