### ISSUE TITLE
CMake RUNTIME_OUTPUT_DIRECTORY for CsCoreTest

### ISSUE THREAD

**Issue by ThomasKrenn** [copperspice/copperspice#186] opened 2021-02-27 11:19 UTC
CMake generates a predefined target RUN_TESTS. 
It would be nice if the target can be executed without any path fiddling from the IDE. 

Please remove the "test" subfolder from CsCoreTest
in .\test\core\CMakeLists.txt

    set_target_properties(CsCoreTest
       PROPERTIES
       RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin"
    )

The batch file "run_coretest.bat" is redundant (except if one wants run only tests using 'catch' only).

Due to the ctest integration one can run tests from the cmake build directory.
ctest.exe --force-new-ctest-process -C ${configuration}

**Comment by bgeller** [comment] 2021-02-27 19:34
In terms of the source code, the Catch tests are not part of the source and therefore belong in a separate folder.  For the exact same reason, we do not want the tests in the "bin" folder since they are not part of the deployment.  

The batch file is necessary and was intended for Windows only, which is why we selected a batch file and not a Bash script. This provides a convenient way for users who do not want to or can not run CTest. Keep in mind CTest does not work for all Windows users due to the inability to set an rpath.   

We are looking at the best way to adjust the rpath for Windows users however the batch file is still of value for some users.

**Comment by ThomasKrenn** [comment] 2021-02-27 23:00
Hello Barbara, 
thanks for your fast answer. 
> not want the tests in the "bin" folder since they are not part of the deployment.

The change would only affect the build step, not the install (deployment) step.

> We are looking at the best way to adjust the rpath for Windows users however the batch file is still of value for some users.

There is no need of any path fiddling if the executable is located in the the binary folder.
In addition users execute the cmake RUN_TESTS target from the GUI (or from the cmd line from the build folder). See screenshot below:

![ksnip_20210227-235747](https://user-images.githubusercontent.com/24775002/109402650-b9b9a880-7957-11eb-9801-27388164ca43.png)

**Comment by ThomasKrenn** [comment] 2021-02-27 23:09
Here is a screenshot of the IDE with CMake Predefined Targets folder enabled. The CMAKE RUN_TESTS target works out of the box if the test executable is in the usual "bin" folder.

![ksnip_20210227-235747](https://user-images.githubusercontent.com/24775002/109402760-ddc9b980-7958-11eb-888b-28957f268467.png)

**Comment by bgeller** [comment] 2021-02-27 23:14
Thanks for your comments, this is a good discussion. 

`The change would only affect the build step, not the install (deployment) step.`

I am aware these files are created during the build process. In our opinion it is inconsistent to have non deploy files directly located in the bin or lib folders.  The best alternative was to move the Catch test executables to a sub folder. 

I know this is a very touchy subject but when we talk about what a user will expect, there is no one answer fits all. We have talked to some of the CMake developers and there are variety of ways to set up and build a given project. Some developers will want one option and other users will want something else.  Every time we do X someone will want Y and the other way around.

We have been looking at a clean why to run CTest on Windows and this change is currently in code review.

**Comment by ThomasKrenn** [comment] 2021-02-28 00:07
> our opinion it is inconsistent to have non deploy files directly located in the bin or lib folders.

That is why one uses CMake. A target needs to be exported/installed before other clients/projects can consume it. 
A "non deploy file (target)" is simply a file that is not exported. (Actually I am not sure if a test target can be exported at all.)

> We have been looking at a clean why to run CTest on Windows 

Provided that the depended shared libraries are found, it works out of the box on all platforms I have tested, due to the cmake RUN_TESTS target (GUI). Or from the command line with:

    ctest.exe --force-new-ctest-process -C ${configuration}

With the -C switch even the configuration can be selected, if the generator support multiple configurations.

**Comment by bgeller** [comment] 2023-12-27 19:47
An update was made back in early 2021 to resolve this problem. Building CopperSpice on Windows will set the runtime path for CTest.  Closing this issue.

**Closed by bgeller** 2023-12-27 19:47 UTC
