### ISSUE TITLE
[MSVC][x86] Copperspice failed to build due to error C2440 on x86 with MSVC on windows

### ISSUE THREAD

**Issue by QuellaZhang** [copperspice/copperspice#297] opened 2024-08-20 05:38 UTC
Hi all,

Copperspice failed to build due to error C2440 on x86 with MSVC on windows, it can be reproduced on cb62036 on master branch. Could you please help look at this issue?

**Environment**:
VS 2022 17.10.5 + Windows Server 2022

**Repro steps:**

1. git clone https://github.com/copperspice/copperspice C:\gitP\copperspice\copperspice
2. open x86 Native tools command prompt for VS2022
3. mkdir C:\gitP\copperspice\copperspice\build_x86
4. cd /d C:\gitP\copperspice\copperspice\build_x86
5. cmake -G "Visual Studio 17 2022" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 ..
6. msbuild /m /p:Platform=Win32 /p:Configuration=Release copperspice.sln /t:Rebuild /p:PreferredToolArchitecture=x64

**Error info:**
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_instance.cpp(110,37): error C2440: '=': cannot convert from 'VkBool32 (__cdecl *)(VkDebugReportFlagsEXT,VkDebugReportObjectTypeEXT,uint64_t,size_t,int32_t,const char *,const char *,void *)' to 'PFN_vkDebugReportCallbackEXT' [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_instance.cpp(443,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkSurfaceKHR' [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(956,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkFramebuffer' [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(959,58): error C2440: 'return': cannot convert from 'const Type' to 'VkFramebuffer' [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(970,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkRenderPass' [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(973,27): error C2440: 'return': cannot convert from 'Type' to 'VkRenderPass' [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(984,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkImage' [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(987,56): error C2440: 'return': cannot convert from 'const Type' to 'VkImage' [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(987,56): error C2440:         with [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(987,56): error C2440:         [ [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(987,56): error C2440:             Type=vk::Image [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(987,56): error C2440:         ] [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(993,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkImageView' [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(996,56): error C2440: 'return': cannot convert from 'const Type' to 'VkImageView' [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(996,56): error C2440:         with [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(996,56): error C2440:         [ [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(996,56): error C2440:             Type=vk::ImageView [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
C:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(996,56): error C2440:         ] [C:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]

**Comment by e-mattes** [comment] 2024-08-21 11:21
Do you really need CsVulkan?

**Comment by QuellaZhang** [comment] 2024-08-22 07:09
Actually, we added "-DWITH_VULKAN=NO" to CMake command line avoid this issue, please feel free to fix it.

**Comment by bgeller** [comment] 2024-08-22 23:49
> Do you really need CsVulkan?

You only need to build this library if you are calling the Vulkan API to display content in a QVulkanWindow. 

1  Please let us know which version of Vulkan you have installed on you build machine. As per our API documentation we require a minimum of the Vulkan SDK version 1.1.124.

2   If you turn off building CsVulkan does your MSVC build finish? 

Barbara

**Comment by bgeller** [comment] 2024-08-31 04:09
We can confirm the CsVulkan library builds correctly on MSVC x86_64.  There is nothing to fix. 

Just curious, is there a reason you are building CopperSpice for 32-bit?

Barbara

**Comment by NEIL-smtg** [comment] 2024-11-05 05:01
@bgeller Actually, we work on MSVC compiler testing, and we regularly build popular open-source project including CopperSpice, with development builds of MSVC in order to find and fix regressions in different target architectures before they ship and cause problems for you. 

> Please let us know which version of Vulkan you have installed on you build machine. As per our API documentation we require a minimum of the Vulkan SDK version 1.1.124.

I'm using Vulkan version 1.3.275.0


> If you turn off building CsVulkan does your MSVC build finish?

Yes, if I build with `-DWITH_VULKAN=NO`, the build succeeded.

I rebuilt CopperSpice today using the latest commit, but I'm still encountering the same issue. Out of curiosity, is there any plan to address this? Feel free to close this if x86 support is no longer intended.

Simple repro:

1. Open x86 native command prompt for VS2022
2. Download [qvulkan_instance.txt](https://github.com/user-attachments/files/17627183/qvulkan_instance.txt)
3. cl /c /std:c++17 /TP /EHsc qvulkan_instance.txt

**Comment by agserm** [comment] 2024-12-24 00:35
We looked at this, and decided supporting Vulkan in 32-bit MSVC builds is not a high priority. If this changes, we will update the ticket.

Thanks for the report.

**Closed by agserm** 2024-12-24 00:35 UTC
